export const PUBSUB_TOPIC_PARENT_TO_CHILD = 'preview-host';

export const PUBSUB_TOPIC_CHILD_TO_PARENT = 'preview';

export const PREVIEW_IFRAME_GLOBAL_VARIABLES_KEY = '__ARCO_PREVIEW_GLOBAL_VARIABLES';
